export const CATEGORY_ACTION_TYPE = {
    SET_CATEGORIES_ARRAY: 'category/SET_CATEGORIES_ARRAY',
    FETCH_CATEGORIES_START: 'category/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'category/FETCH_CATEGORIES_FAILED',
}